trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - package.json
      - package.lock.json
      - '*/package.json'
      - '*/package.lock.json'
      - '*package.json'
      - '*package.lock.json' 
      
      

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    git config --global user.email "alejandro.iglesias@trifenix.io"
    git config --global user.name "alejandro.iglesias"    
    git clone https://ale:tztflymo4joqivpd7yj2jqzwekko3owafvhqtzpbk5xxgzkcaqxa@dev.azure.com/Trifenix-Agricola-JHM/Components/_git/component-semantic-styled temp
    cd temp    
    git checkout master
    npm version patch    
    git push origin master
    cd .. 
    cp -rf temp/package.json package.json
    cat package.json
  displayName: 'Update version'

- script: |        
    npm install    
  displayName: 'npm install packages'

- script: |    
    npm run build    
  displayName: 'npm build packages'

- script: |
    npm pack
  displayName: 'Package for npm release'



- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy Build'


- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/npm'
    artifactName: npm
  displayName: 'Publish npm artifact'

